In [148]:
# Python program to find maximum prizes in a 4*n matrix Q
# such that no two squares are adjacent. 
import numpy as np

def maxPrizes(Q, n) :
    
    def get_key(val):
        for key, value in P.items():
             if val == value:
                return key
            
    #base case, P is a dic containing 8 cases with its binary combination. OPT is a 8 * n matrix
    P = { 0:0, 1:1, 2:2, 3:4, 4:5, 5:8, 6:9, 7:10 }
    PATT = 0
    OPT = np.zeros((8, n))
    for i in range(n-1) :
        for p in P.values():
            for k in P.values():
                #find the total feasible prizes in the ith row
                if ((k & p) == 0):
                    if p == 1:
                        PATT = Q[3][i]
                    elif p == 2:
                        PATT = Q[2][i]
                    elif p == 4:
                        PATT = Q[1][i]
                    elif p == 5:
                        PATT = Q[1][i] + Q[3][i]
                    elif p == 8:
                        PATT = Q[0][i]
                    elif p == 9:
                        PATT = Q[0][i] + Q[3][i]
                    elif p == 10:
                        PATT = Q[0][i] + Q[2][i]
                    else:
                        PATT = 0
                #Iteration over OPT and PATT 
#                 print(PATT)
                OPT[get_key(p)][i] = max((OPT[get_key(k)][i-1] + PATT), OPT[get_key(p)][i-1])
                PATT = 0
    #return the max value of prizes among all OPT
    print(OPT)
    return max((OPT[m][n-1]) for m in range(8))


if __name__ == "__main__" : 
 
    Q =   [ [ 1, 2, 3, 4, 5], 
            [ 6, 7, 8, 9, 10],
            [ 1, 2, 3, 4, 5],
            [ 1, 2, 3, 4, 5]]
    n = 5
    print(maxPrizes(Q, n))


[[ 0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 6.  7.  8.  9.  0.]
 [ 7.  9. 11. 13.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
0.0


In [48]:
a = 8
b = 9
print(a & b)

8


In [17]:
import numpy as np

n = 10
r = [1,5,1]

def min_access_time() :
    OPT = np.zeros((n,n,len(r)+1))
    for i in range(n-1,-1,-1):
        for j in range(n):
            for p in range(len(r)-1,-1,-1):
                OPT[i][j][p] = min((OPT[int(r[p])][j][p+1] + 
                                    abs(i - int(r[p]))), 
                                   (OPT[i][int(r[p])][p+1] + 
                                    abs(j - int(r[p]))))
    print(OPT[0][n-1][0])  
min_access_time()

5.0


In [14]:
import numpy as np
M = [[0,0,1,1],
     [0,0,0,1],
     [1,0,0,0],
     [1,1,0,0]]
n = 4
OPT = np.zeros((n,n))
def max_cake():
    OPT[0][n] = n+1
    for i in range(0,n):
        for j in range(n,i):
            if (i <= j):
                OPT[i][j] = M[i][j] + OPT[i][j - 1]
    print(OPT[0][0])
max_cake()

IndexError: index 4 is out of bounds for axis 0 with size 4